# Generated by Django 3.2 on 2021-05-23 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('post', models.TextField(max_length=3000)),
                ('image', models.ImageField(upload_to='blogimage')),
                ('thumbnail', models.ImageField(upload_to='blogthumb')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('pdf', models.FileField(upload_to='bookspdf')),
                ('thumbnail', models.ImageField(upload_to='booksthumb')),
            ],
        ),
    ]
