# Generated by Django 3.2 on 2021-05-26 12:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='post',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
