# Generated by Django 3.2 on 2021-05-23 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='cart',
            field=models.ManyToManyField(blank=True, related_name='bookcart', to='bookstore.Book'),
        ),
        migrations.AlterField(
            model_name='library',
            name='owned',
            field=models.ManyToManyField(blank=True, related_name='mybook', to='bookstore.Book'),
        ),
        migrations.AlterField(
            model_name='library',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='wishbook', to='bookstore.Book'),
        ),
    ]
